name: demopetnest
description: "A new Flutter project for Petnest."
publish_to: 'none'

# The version of your application.
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Using a stable version of lints for better code quality
  flutter_lints: ^3.0.0

flutter:
  # Enables Material Design components and Material Icons
  uses-material-design: true

  # Asset management
  assets:
    - assets/images/
    # If you have specific fonts, uncomment and add them below:
    # - assets/fonts/
